[package]
name = "lang"
version = "0.1.0"
edition = "2021"

build = "build.rs" # LALRPOP preprocessing

[dependencies]
lalrpop-util = "0.20.0"
logos = "0.13.0"

[build-dependencies]
lalrpop = { version = "0.20.0", default-features = false }